version: "3.7"
volumes:
  pgadmin_data:
    driver: local

networks:
  golculator:
    driver: bridge

services:

  db:
    image: postgres:13.2-alpine
    hostname: db
    ports:
      - "${DB_PORT}:5432"
    container_name: db
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_DB: "${DB_NAME}"
    networks:
      - golculator

  service:
    image: localhost:5000/golculator:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: service
    hostname: service
    restart: unless-stopped
    expose:
      - ${APP_PORT}
    environment:
      DB_HOST: "db"
      DB_PORT: "5432"
      DB_USER: "${DB_USER}"
      DB_PASSWORD: "${DB_PASSWORD}"
      DB_NAME: "${DB_NAME}"
      APP_PORT: "${APP_PORT}"
      ENVIRONMENT: "Docker"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - golculator

  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    container_name: nginx
    restart: unless-stopped
    ports:
      - "${APP_PORT}:8989"
    depends_on:
      - service
    networks:
      - golculator